server.port=8088
spring.application.name=admin-service

# Database (specific DB for admin)
spring.datasource.url=jdbc:mysql://localhost:3307/admindb
spring.datasource.username=root
spring.datasource.password=142312
