# Server
server.port=8083

# Application Name
spring.application.name=car-service

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3307/cardb
spring.datasource.username=root
spring.datasource.password=142312
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Enable tracing
management.tracing.sampling.probability=1.0

# Zipkin URL
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Expose actuator endpoints
management.endpoints.web.exposure.include=*

spring.config.import=optional:configserver:http://localhost:8888
